GLOBAL_LIST_INIT(smash_sound,list('sound/effects/gore/smash1.ogg', 'sound/effects/gore/smash2.ogg', 'sound/effects/gore/smash3.ogg', 'sound/effects/gore/trauma1.ogg'))
GLOBAL_LIST_INIT(heavystep_sound,list('sound/effects/x1.ogg','sound/effects/x2.ogg','sound/effects/x3.ogg','sound/effects/x4.ogg'))
GLOBAL_LIST_INIT(light_strike_sound,list('sound/effects/hit_kick.ogg', 'sound/effects/hit_punch.ogg'))
GLOBAL_LIST_INIT(gun_sound, list('sound/weapons/gunshot.ogg', 'sound/weapons/gunshot2.ogg', 'sound/weapons/gunshot3.ogg', 'sound/weapons/gunshot4.ogg'))
GLOBAL_LIST_INIT(human_clearing_throat, list(FEMALE = "infinity/sound/voice/clearing-throat-f.ogg", MALE = "infinity/sound/voice/clearing-throat-m.ogg"))
