/obj/structure/railing/attack_hand(mob/user)
	if(isxenomorph(user))
		user.visible_message(SPAN_DANGER("[user] tears to pices [src] with it's claws!"), SPAN_DANGER("You tear [src]!"))
		take_damage(20)
	..()