/decl/cultural_info/location/root
	secondary_langs = list(LANGUAGE_SPACER, LANGUAGE_INDEPENDENT, LANGUAGE_SIGN, LANGUAGE_GUTTER, LANGUAGE_LUNAR, LANGUAGE_SOL_COMMON, LANGUAGE_RESOMI, LANGUAGE_SIIK_MAAS, LANGUAGE_SKRELLIAN, LANGUAGE_UNATHI)
