/decl/cultural_info/location/root
	secondary_langs = list(LANGUAGE_SPACER, LANGUAGE_HUMAN_RUSSIAN, LANGUAGE_SIGN, LANGUAGE_GUTTER, LANGUAGE_HUMAN_EURO, LANGUAGE_RESOMI, LANGUAGE_SIIK_MAAS, LANGUAGE_SKRELLIAN, LANGUAGE_UNATHI_SINTA)
