#include "abductor_equip.dm"
#include "abductor_glands.dm"
#include "abductor_machinery.dm"
#include "abductor_structures.dm"
#include "abductor_tools.dm"
#include "maps\antag_spawn\abductors\abductors_inf.dm"