/obj/item/weapon/storage/belt/utility/full_buy/New()
	..()
	new /obj/item/weapon/screwdriver(src)
	new /obj/item/weapon/wrench(src)
	new /obj/item/weapon/weldingtool(src)
	new /obj/item/weapon/crowbar(src)
	new /obj/item/weapon/wirecutters(src)
	new /obj/item/device/multitool(src)

/obj/item/weapon/storage/belt/medical/emt/combat
	name = "combat medical belt"

/obj/item/weapon/storage/belt/medical/emt/combat/New()
	..()
	new /obj/item/weapon/storage/pill_bottle/dylovene(src)
	new /obj/item/weapon/storage/pill_bottle/dexalin(src)
	new /obj/item/weapon/storage/pill_bottle/spaceacillin(src)
	new /obj/item/weapon/storage/pill_bottle/bicaridine(src)
	new /obj/item/weapon/storage/pill_bottle/inaprovaline(src)
	new /obj/item/weapon/storage/pill_bottle/tramadol(src)
	new /obj/item/weapon/storage/pill_bottle/kelotane(src)

/obj/item/weapon/storage/belt/holster/security/ocei/New()
	..()
	new /obj/item/taperoll/police(src)
	new /obj/item/weapon/melee/baton/loaded(src)
	new /obj/item/device/flashlight/maglight(src)
	new /obj/item/weapon/handcuffs(src)
	new /obj/item/ammo_magazine/pistol(src)
	new /obj/item/ammo_magazine/pistol(src)
	new /obj/item/weapon/gun/projectile/pistol/sec(src)

/obj/item/weapon/storage/belt/holster/security/tactical/troops/New()
	..()
	new /obj/item/ammo_magazine/smg_top(src)
	new /obj/item/ammo_magazine/smg_top(src)
	new /obj/item/ammo_magazine/smg_top(src)
	new /obj/item/ammo_magazine/smg_top(src)
	new /obj/item/ammo_magazine/smg_top(src)
	new /obj/item/ammo_magazine/smg_top(src)
	new /obj/item/weapon/gun/projectile/pistol/sec(src)
	new /obj/item/ammo_magazine/pistol(src)

/obj/item/weapon/storage/belt/holster/security/tactical/troops_sts/New()
	..()
	new /obj/item/ammo_magazine/rifle(src)
	new /obj/item/ammo_magazine/rifle(src)
	new /obj/item/ammo_magazine/rifle(src)
	new /obj/item/ammo_magazine/rifle(src)
	new /obj/item/ammo_magazine/rifle(src)
	new /obj/item/ammo_magazine/rifle(src)
	new /obj/item/weapon/gun/projectile/pistol/sec(src)
	new /obj/item/ammo_magazine/pistol(src)
