name: Отметка устаревших отчётов и запросов на слияние

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: "Этот PR был неактивен достаточно долго, поэтому он был автоматически помечен как устаревший. Это означает, что существует риск того, что он будет автоматически закрыт через ~ 7 дней. Пожалуйста, устраните все нерешенные вопросы и убедитесь, что ваш PR завершен. Если ваш PR готов, вы должны попросить специалиста по обслуживанию удалить устаревшую метку на вашем PR, чтобы сбросить таймер. Если вы думаете, что за это время ни один сопровождающий не ответит, вы можете закрыть этот PR самостоятельно и переоткрыть его когда будете готовы."
        days-before-stale: 7
        days-before-close: 7
        stale-pr-label: 'Stale'
        exempt-pr-label: 'RED LABEL'
